r-lib/scales

R/pal-shape.r

Alternative punctuation: "Consider specifying shapes manually. If you must have them."

Removed stray period

---

NEWS
R/pal-brewer.r
man/brewer_pal.Rd

Use the same argument that hue_pal uses: direction

Allow to reverse the order of colours in a brewer palette

---

DESCRIPTION
NEWS.md
cran-comments.md

In prep for the next release of `scales` I've updated the version number and cran-comments.md. Is this the right information to include? This will be my first CRAN submission 😮 so I'm not sure what info they need.
Also I might've misinterpreted the instructions in our doc—I only built on Windows with R-devel, not R-release. Let me know if you want me to re-do that on both.

Update CRAN comments and version for next release

---

DESCRIPTION
tests/testthat/test-bounds.r

`bit64` is only suggested because it appears on a unit test I wrote (#75).
As it is a suggested package, the test should be skipped if `bit64` is missing.
This hopefully has the positive side effect of making Dirk Eddelbuettel happier http://dirk.eddelbuettel.com/blog/2017/03/22/

Skip bit64 unit test if not installed

---

DESCRIPTION
R/pal-gradient.r
man/div_gradient_pal.Rd

This pull request updates the example in `div_gradient_pal()` that relies on munsell, and wasn't producing expected output as documented in #127 
Bump in version of munsell required since updated example won't work with old munsell.

Fix munsell example in div_gradient_pal, fixes #127

---

NEWS.md
R/trans-date.r
tests/testthat/test-trans-date.r

This PR adds a new function, `time_format`, to format times properly, for both `POSIXt` and `hms` objects.  A separate function made more sense to me than did adjusting `date_format` to accommodate times, but if this code feels too redundant, I'm happy to implement changes to `date_format` instead.
I also wonder if date_format and/or time_format shouldn't be moved to formatter.r with all the other formatters. 
Addresses #88
-----------
Some notes about handling timezones for hms objects: 
For consistency, it seemed important to continue using standard POSIX specification for formatting, but while time zone of hms objects can be specified at conversion (from other datetime classes, defaults to local time) but they not have a tzone attribute themselves and can't/don't respect daylight …

Add time_format() function for time formatting

---

R/colour-manip.r
man/col_numeric.Rd
man/show_col.Rd

the same here as [#87](https://github.com/r-lib/scales/pull/87), from an updated fork.
problem: trying to plot great enough matrices ( 400X400 on...) produces unreadable labels
proposed solution: giving the user control over label size.
@dpseidel code is formatted following the tidy style.

added label size control to show_col()

---

NEWS.md
R/formatter.r
man/scientific_format.Rd
tests/testthat/test-formatter.r

Consistent with the arguments introduced by `number_format()`

Additional arguments for scientific_format()

---

NEWS.md
R/breaks.r

Fixes #99 
As the default of `only.loose = FALSE` in `labeling::extended()`, it seemed unnecessary to expose it as a parameter to `extended_breaks()` but it is no longer forced to `FALSE`, fixing #99.

Free `only.loose` argument inside `extended_breaks()`

---

NEWS.md
R/formatter.r
man/dollar_format.Rd
tests/testthat/test-formatter.r

`dollar_format()` rely on `number_format()`

---

NEWS.md
R/bounds.r
tests/testthat/test-bounds.r

This seemed the most logical and minimal fix but if you have a different idea, let me know.  Previously in expand_range(), `zero_width` was divided in half and added or subtracted on either side of the axis tick, resulting (from defaults) in a range of 1 (so when the original issue poster called `geom_boxplot(width=0)` there was no padding). Now instead, `zero_width` functions as our `diff(range)` and the equation matches that of non-zero ranges, respecting `mul` and `add`. 
This fixes (the scales side of) the original issue (respecting `mul` and `add` parameters) but single ticket facets specifying a boxplot `width` ≥  than this range will still look tight. Looking into this further I found some weird bugs happening with the `width` argument to `geom_boxplot` and `geom_violin`. Will open …

Adjust expand_range() so zero range scales respect mul and add

---

NEWS.md
R/breaks.r
tests/testthat/test-breaks-log.r

Make log_breaks work with very small ranges

---

NEWS.md
R/range.r
tests/testthat/test-range.r

In trying to covert ggplot2 to use scales exported `Range` objects (tidyverse/ggplot2#2710), I realized that the R6 inheritance was broken. This PR fixes that. Unfortunately this likely means that conversion in ggplot2 needs to wait until the next scales release.

Fix R6 inheritance

---

R/formatter.r
man/number_format.Rd

There seems to be an error related to building the PDF manual causing the following PRs to fail:
-  #198 
- #197 
- #195 
The error is:
```
LaTeX errors found:
! Package inputenc Error: Unicode char ≥ (U+2265)
(inputenc)                not set up for use with LaTeX.
```
which is caused by the use of the `≥` symbol in the docs for `number_format()`. I've changed the offending symbol.

latex doesn't like unicode character for >=

---

NEWS.md
R/breaks.r

This PR modifies the function returned from the different breaks constructors to allow changing `n` after the constructor call. The value of the `n` argument in the constructor call will be used as a default for the `n` argument in the returned functions, meaning that no code should break with this addition.
This change is necessary in order to allow direct changing of desired break frequency in the `scale_*` functions in ggplot2

Add n argument to the function returned by the breaks constructors

---

NEWS.md
R/colour-manip.r
man/alpha.Rd
tests/testthat/test-alpha.r

The `alpha()` function now preserves names on the elements.  I followed the approach used earlier in the file for `col2hcl()`.
https://github.com/r-lib/scales/blob/51547d6865f61f8cc0239063bacc619dce8a35b6/R/colour-manip.r#L26
A common use case for me is when I create palette to pass to the `values` parameter of `ggplot2::scales_color_manual()` and `ggplot2::scales_fill_manual()`.  Like the [chapter 5 scatterplots here](
https://github.com/OuhscBbmc/DeSheaToothakerIntroStats/blob/master/thumbnails/thumbnails.md) (and  countless people before me), the scatterpoints are darker around the edges, but translucent in the center.  I need explicit vector names to force colors to be consistent across plots, even if a factor level is missing.
Instead of replicating the rgb components like:
```r …
```

preserve element names in `alpha()`

---

DESCRIPTION
R/colour-ramp.R

Fix #241 This PR restores the old behaviour of treating NA input as `'transparent'` when creating a `colour_ramp()`

keep grDevices-style NA handling in colour_ramp

---

NEWS.md
R/pal-hue.r
tests/testthat/test-pal-hue.r

scales 1.1.0 replaced `grDevices::hcl` with `farver::encode_colour` breaking the `direction  = -1` functionality  for `hue_pal`. Original functionality relied upon parsing negative hue values. 
This new implementation matches our current handling of the direction argument in `brewer_pal` using the `rev` argument to simply reverse the palette returned when `direction = -1`.  This is different from the implementation used in scales 1.0.0 (see below) which returns colors from the opposite side of the color wheel, but I think this actually is more consistent with expected `direction = -1` behavior for discrete scales. 
``` r
show_col(hue_pal(direction = 1)(4))
```
scales 1.0.0 
``` r
show_col(hue_pal(direction = -1)(4))
```
scales 1.1.0
``` r
show_col(hue_pal(direction = -1)(4))
```
scales …

Fix direction = -1 functionality for `hue_pal` (#252)

---

R/range.r

DiscreteRange train function does not currently support the `na.rm` argument to `train_discrete`,  preventing its direct use to replace ggplot2's range functions (tidyverse/ggplot2#2710). This PR updates the train function to support this argument.

Add na.rm support to DiscreteRange$train

---

man/viridis_pal.Rd

The dev version of viridisLite has 3 more options, so we need to update the document once it's released. This pull request might be a bit too early and I'll reflect the released version of the document.
https://sjmgarnier.github.io/viridisLite/reference/viridis.html

Reflect more options to viridis_pal()

---

NEWS.md
R/label-number-auto.R
tests/testthat/test-label-number-auto.R

Fixes #321. `vapply()` would return a character vector instead of a matrix when formatting a single value, which then caused `apply()` to throw an error. This ensures that we're calling `apply()` on a matrix with the necessary dimensions.

Fix `label_number_auto()` to work on single values > 1e+06 

---

NEWS.md
R/label-number.r
tests/testthat/test-label-dollar.R
tests/testthat/test-label-number-si.R
tests/testthat/test-label-number.r
tests/testthat/test-label-percent.R
tests/testthat/test-labels-retired.R

Fixes #279
The auto accuracy heuristic shows 2 significant figures, relative to the smallest difference between breaks. This is designed to handle situations like (taken from [tidyverse blog post](https://www.tidyverse.org/blog/2019/11/scales-1-1-0/)):
However, this heuristic displays an unnecessary digit in the specific case when all the breaks align with zeros in the final digit. This situation naturally occurs very often. Here's an example (taken from the [scales docs](https://scales.r-lib.org/reference/label_number_si.html)):
This PR reduces the precision when final digit is always zero.
``` r
library(scales)
number(seq(0, 0.1, 0.025))
#> [1] "0.000" "0.025" "0.050" "0.075" "0.100"
number(seq(0, 20, 5))
#> [1] "0.0"  "5.0"  "10.0" "15.0" "20.0"
```
<sup>Created on 2021-03-27 by the …

Adjust auto accuracy heuristic

---

NEWS.md
R/trans-compose.R
R/trans-numeric.R
R/trans.R
man/probability_trans.Rd
man/trans_new.Rd
tests/testthat/test-trans-compose.R
tests/testthat/test-trans-numeric.R

This PR closes #322 by supplying derivatives of transformation functions and inverses where possible.
Specifically, it:
- Adds two optional, may-be-`NULL` fields to transform objects: `$d_transform` and `$d_inverse`. These functions are the derivatives of `$transform` and `$inverse`.
- Supplies derivatives for all existing numeric transformations
- Applies the chain rule to give derivatives for `compose_trans()` (unless any derivatives in the transformation are missing, in which case the corresponding derivative function is `NULL`).
- Includes tests for all of the above.
Some possible discussion points:
- I initially used `$transform_deriv` and `$inverse_deriv`, but found that existing tests used partial matching on `$trans` and `$inv`, so these names caused failures. I wasn't sure if …

Derivatives of transformations

---

NEWS.md
R/trans-compose.R
tests/testthat/_snaps/trans-compose.md
tests/testthat/test-trans-compose.R

This PR corrects the domain calculations for `compose_trans()`, which appear to be incorrect. 
Currently, `compose_trans()` pushes the domain of the first function through all transformations to calculate the domain. This procedure, when it works (i.e. if the range of each transformation in the chain is contained within the domain of the next one), yields the *range* of the composed set of transformations, not the domain.
This leads to incorrect domains; e.g.:
```r
compose_trans("sqrt", "reverse")$domain
```
The correct domain here is just the domain of `sqrt()`, which is `c(0, Inf)`. We can see this by plotting it:
```r
plot(compose_trans("sqrt", "reverse"), xlim = c(-1,4))
```
This also leads to `compose_trans()` incorrectly erroring on valid compositions; e.g.:
```r …
```

Correct domain calculation for compose_trans

---

R/transform-numeric.R

The documentation of the Box-Cox transformation is not correct. It confuses the parameters $y$ and $\lambda$.
This PR corrects it.
To be convinced, read the equations in the Details section. $y$ may take any value but the fractions are 0/0 when $\lambda = 0$.

Confusion between y and lambda in the documentation of the Box-Cox transformation 

---

R/label-number.R
tests/testthat/test-label-number.R

This pull request resolves #413, implementing the fix proposed by @jbengler ([link](https://github.com/r-lib/scales/issues/413#issuecomment-1859304601))
Behaviour in 1.3.0:
```
> scales::label_number(scale_cut = scales::cut_short_scale())(c(0,500,1500,2000,2500))
Error in break_suffix[bad_break][improved_break & !power10_break] <- names(lower_break[improved_break &  : 
NAs are not allowed in subscripted assignments
```
Behaviour after change (as expected):
```
> scales::label_number(scale_cut = scales::cut_short_scale())(c(0,500,1500,2000,2500))
[1] "0"    "500"  "1.5K" "2.0K" "2.5K"
```
This change does not break any package tests, and I have added an additional test against this behaviour.
```
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 597 ]
```

fix bug in `label_number` when `scale_cut` argument is provided (#413)

---

R/label-date.R
man/date_format.Rd
man/label_date.Rd

The docs were confusingly referencing the superseded `date_format` `time_format` and `date_short` functions.

Update label-date documentation

---

R/label-pvalue.R

The documentation of the `prefix` argument appears to be opposite of the actual code; here's a PR to fix.

fix typo in documentation for `label_pvalue()`

---

R/pal-shape.r

I accidentally transposed a couple of aesthetic mappings while constructing a plot yesterday and was (rightfully) warned about my request for 25 different shapes. However, I noticed that the wording of the warning was a little strange/confusing (emphasis mine):
> you have requested 25 values. Consider specifying shapes manually if you need **that many have them**.
It looks like this happened unintentionally in 45ca806b: the message originally read "if you must have them." This PR rewords it to "if you need that many of them," but I'm not attached to this particular phrasing.

Update warning message for shape overuse

---

R/utils.R

As pointed out off-github, there was a non-existing `xs` variable that was returned via `recycle_common()`.
Upon further reflection, we can never reach the state wherein that value had to be returned, so in this PR we remove it.

Remove unreachable branch of logic in `recycle_common()`

---

R/label-date.R
R/label-number.R
R/pal-dichromat.R
man/comma.Rd
man/date_format.Rd
man/label_bytes.Rd
man/label_currency.Rd
man/label_date.Rd
man/label_number.Rd
man/label_number_si.Rd
man/label_ordinal.Rd
man/label_percent.Rd
man/number.Rd
man/pal_dichromat.Rd

This PR fixes a handful of very minor typos that I found while reading the documentation, only one of which is associated with an issue that is linked in the commit. roxygenize was not executed because there is a GitHub action to do so upon pull requests and I have a different version of the package than the package description.
* continous to continuous
* hypen to hyphen
* adds "to" after "Use `label_number()`
* adds missing ] to [label_date()/[label_time()]

fix typos; spelling and missing bracket

---

R/bounds.R

This PR aims to fix #468 and by extension fix https://github.com/tidyverse/ggplot2/issues/6134.
Briefly, we cast input `x` to numeric before doing computations for the range.
``` r
devtools::load_all("~/packages/scales//")
#> ℹ Loading scales
range <- structure(c(1234, 7380), class = "difftime", units = "secs")
zero_range(range)
#> [1] FALSE
ggplot2::resolution(range, zero = FALSE)
#> [1] 6146
```
<sup>Created on 2024-10-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

`zero_range()` casts to numeric

---

NEWS.md
R/transform-numeric.R

As title indicates.
For posterity, we're leaving out this change for now because it breaks one of ggplot2's tests.
We can integrate the breaks again when ggplot2 is ready.

Leave out integration with `transform_exp()` for now

---

NEWS.md
R/scale-continuous.R
R/scale-discrete.R
tests/testthat/_snaps/scale-continuous.md
tests/testthat/test-scale-continuous.R
tests/testthat/test-scale-discrete.R

This PR aims to fix #480.
For discrete training, `is.factor(x)` is swapped out by `!is.null(levels(x))`.
That way, any custom class that implements `levels.custom()` should be able to train a range.
For continuous training, we require the result of `range(x)` to be numeric (rather than x itself).
Error message is slightly terser, but that isn't too bad.
``` r
devtools::load_all("~/packages/scales")
#> ℹ Loading scales
#> Warning: package 'testthat' was built under R version 4.4.2
library(vctrs)
newdisc <- new_list_of(x = list("A", c("B", "C")), ptype = character(), class = "foo")
levels.foo <- function(x) unique(unlist(x))
train_discrete(newdisc)
#> [1] "A" "B" "C"
newcont <- new_list_of(x = list(1, c(5, 3)), ptype = double(), class = "bar")
range.bar <- function(x, ...) range(unlist(x), …
```

Train custom classes

---

R/breaks.R
R/scale-continuous.R
R/scale-discrete.R

This PR aims to fix a few breakages discovered in 72544e6.
If the revdepcheck would be run again, I expect ggprism to remain broken because of a fragile test.
I couldn't reproduce the error in Karen, so I've ignored this.

Fixes for bugs discovered in revdepcheck
